### ISSUE TITLE
No createContainer ?

### ISSUE THREAD

**Issue by eggerdo** [jdrouet/loopback-component-storage-mongo#9]
Why is there no `createContainer` API available, although it says so in the README? Are you planning on amending that any time soon?

**Comment by jdrouet** [comment]
@eggerdo in this component, the container is abstract. It's just a tag in the metadata of the file stored in MongoDB. In that way, I don't think that a create method would be interesting.

**Comment by eggerdo** [comment]
@jdrouet ah ok, so basically the `createContainer` is done as part of an upload. Thought I need to create first the container before I can reference it in the upload.
But then maybe take it ouf of the README since it's not a separate API call?

**Comment by jdrouet** [comment]
@eggerdo I've planned to add to the README more informations. But you don't have to do anything before uploading your file. Upload it and specify the name of your container, and it'll be created.

**Comment by eggerdo** [comment]
OK understood, thanks :)
